### PR TITLE
Update RF24Mesh_Example_Node2Node.ino

### PR DESCRIPTION
**Pull request by Avamander**
RF24Mesh reports messages received from master as nodeID for some reason, I added a workaround.

### CODE REVIEW

**Comment by TMRh20** [comment]
My intent was to just display the nodeID of all messages received, so the master node should be reported as nodeID 0. Does this seem odd or??

**Comment by Avamander** [comment]
The workaround was added just for the reason Master is not reported as 0 but as nodeID. 

The workaround I added just fixes that problem by checking if received message origin node number is the same as the node that received the message (if it seemingly sent itself a message) if it does, then it knows the message is from the master.

**Comment by TMRh20** [comment]
Well, per the commit noted above, I just broke your fix, bit fixed the bug that it identified. 

The getNodeID() function was previously used to get the local nodeID. When this changed to perform lookups, I neglected to realize that doing a lookup on the master node would result in the local ID being returned. The current code fixes this, and returns -1 if the lookup fails, local ID if it is called with no input, and master will return 0 as it should.

The only thing left to do is fix the example, to check for a return value of >=0 or >-1 instead of >0 , so please either update your pull, or I can make the change.

**Comment by Avamander** [comment]
You make the change if you feel that it's necessary. I'll close my pull request as it's no longer relevant.

**Pull request closed without merging**
