### PR TITLE
New remove node function and new field in addrliststruct

### PR DESCRIPTION
**Pull request by ricmail85**
Hi,
I have slightly modified the lib in order to allow the user to edit the meshlist of nodeIDs.
Now there is a function mesh.remove(int16_t nodeID) that removes (if it exists) the node from mesh.

Moreover I added a new field in the addrListStruct, called lastTime that is updated automatically by mesh.update().
This is useful in order to know the last activity of a certain node. From the combined use of these two, the user can automatically delete a node if there has not been any activity for a while.

### CODE REVIEW

**Comment by Avamander** [comment]
Do you know how much did the examples grow in size without actually using the feature?

**Comment by ricmail85** [comment]
Actually I don't know. I compiled everything and it seems to work on my arduinos...

**Comment by Avamander** [comment]
Could you please check? Though, we could push this into a new testing
branch and let people use that and when it seems perfect we push it to
master?

**Comment by ricmail85** [comment]
Ok, What I should check in particular? the size of the free memory left on arduino or what?

**Comment by Avamander** [comment]
Used flash and memory new vs. old.

**Comment by ricmail85** [comment]
Here the numbers:

RF24_Mesh_Example_Master: Sketch uses 11,518 bytes (4%) of program storage space. Maximum is 253,952 bytes. Global variables use 655 bytes (7%) of dynamic memory, leaving 7,537 bytes for local variables. Maximum is 8,192 bytes.

RF24_Mesh_Example: Sketch uses 10,822 bytes (4%) of program storage space. Maximum is 253,952 bytes.
Global variables use 691 bytes (8%) of dynamic memory, leaving 7,501 bytes for local variables. Maximum is 8,192 bytes.

**Comment by TMRh20** [comment]
This looks pretty good, I like the remove() functionality.  

> Though, we could push this into a new testing
branch and let people use that and when it seems perfect we push it to
master?

@Avamander Sounds like a plan

@ricmail85 
Are those numbers the new numbers? Can we get a comparison?
  
I have a few questions/concerns about the updateNodeTime() function:
 1. The endif [here] https://github.com/ricmail85/RF24Mesh/blob/5b52106f96f67b36dac67cb3d2ff81765970e389/RF24Mesh.cpp#L123) should probably be moved under the upateNodeTime stuff, so it is only called on the master?

 2. It looks like the update is done whenever mesh.update() is called, regardless of whether a payload was received. This should catch whatever payload was received last, but may miss some user payloads as well as making duplicate updates.

This (2) is actually a pretty creative solution, which will probably work. I've been thinking more at trying to add something at the network level, in respose to NETWORK_PING/mesh.checkConnection() but this is maybe better.

Also, in the examples, EEPROM.h is not needed anymore, the nodeID is just saved in program memory, so that can be removed.

**Comment by ricmail85** [comment]
Hi,
yes I put in the mesh.update() routine in order to catch any message catched by the master... Not only user messages (in principle, we don't know if the user want to send something to the master/other nodes...). In that way also the system messages are used in order to keep under control the timing of all nodes. That's why it's under mesh.upate().

I slightly modified the routine in order to works only on the master node.

**Comment by TMRh20** [comment]
Merged into https://github.com/TMRh20/RF24Mesh/tree/Testing for ... testing

**Pull request merged**
