### PR TITLE
Create RF24Mesh_Example_Master_To_Nodes.ino

### PR DESCRIPTION
**Pull request by Avamander**
This is a Frankenstein I created from Master and Master_Statics. This sketch that sends node 1 every five seconds a message. As a beginner this is the best I could come up with. Nodes must have RF24Network listening code to get the message.

### CODE REVIEW

**Comment by ppotok** [comment]
Wow thanks this one helps me. I am wondering if it is not better to put it inside RF24Mesh::getAddress or  generally use mesh.write?  Also how looks "receiving" station please?

**Comment by Avamander** [comment]
This was the only working solution that actually worked easily. Receiving node has to have:

while (network.available()) {
    RF24NetworkHeader header;
    payload_t payload;
    network.read(header, &payload, sizeof(payload));
    Serial.print("Received packet #");
    Serial.print(payload.counter);
    Serial.print(" at ");
    Serial.println(payload.ms);
  }

**Comment by TMRh20** [comment]
This is pretty good, and ties in nicely with the existing node example.

I've added a couple minor changes here: https://gist.github.com/TMRh20/f21ec7e5e666e83b082a

1. Remove EEPROM include (no longer needed, but still in a lot of the example sketches etc.)
2. Add ctr variable for numbering payloads
3. Modify to send millis() & counter to every node in 5-second intervals, with a different message going to node1
4. Add serial.print to show success or failure of each write

If you want to add these in, you can just update your fork, and it should update this commit too, else suggestions etc. are welcome.

If you want to do another pull request against the standard RF24Mesh_example sketch ( to include your additional RX code ) that would be great, because then the one sketch will work with both master examples.

**Comment by Avamander** [comment]
Updated this sketch.

**Pull request merged**
