### PR TITLE
Dynamic NodeID configuration

### PR DESCRIPTION
**Pull request by spaniakos**
Dynamic NodeID assigment sketch
hope is working for you as well.
:)
@TMRh20 you can find the code to download to my fork

the only think a cannot fix is the auto dhcplist.txt write.
i dont know why its nto handled with the mesh.update automatically.
(i use od -c dhcplist.txt to see the addresses)

some times after the reset of the client, the numbers is writen to the dhcplist.txt, while some other times it can go several minutes without writing.

plus some time (i assume thats happening by change) the 377(octal) is writen in the dhcp (as this is my master NodeID for now. but this can easylly be filtered inside the saveDHCP function.

thanks

### CODE REVIEW

**Comment by spaniakos** [comment]
the only think a cannot fix is the auto dhcplist.txt write.
i dont know why its nto handled with the mesh.update automatically.
(i use od -c dhcplist.txt to see the addresses)

**Comment by TMRh20** [comment]
Thanks for sharing your code, this gives me some ideas and raises some questions as well. 
   
There are still some design issues/flaws/considerations with RF24Mesh that I haven't quite come to terms with, and the dhcplist.txt saving method is one. (It only saves when the address list is updated, and only at a maximum of once per 300ms) A set, timed interval that records all changes may be a better solution, and should let you re-write the address list however you want.  
  
As per http://arduino.cc/en/Reference/EEPROMWrite  "The EEPROM memory has a specified life of 100,000 write/erase cycles, so you may need to be careful about how often you write to it." So it might be beneficial to tweak the eeprom stuff to ensure writing is kept to a minimum in case of continuous resets or other odd or strange behaviour.  
   
All in all, It seems like this would be a viable option. There are potentially some issues with dynamic nodeID assignment, like duplicate nodeIDs if the dhcplist is wiped, which could just use a separate file or something, and, of course, it does obscure which nodes are which, but it seems workable.  
  
I'll hopefully get some time to work on some of the RF24Mesh issues soon, but due to the nature of things right now, I can't say exactly when.

**Comment by spaniakos** [comment]
No problen , i am glad to help.

For the EEProm issue . If the dynamic ID is embeded to the library, the
dhcp list cab be wiped with every RPi restart. That will lead us to a point
that with every node connection the dhcp will grand a dynamic id, which
will last only for the uptime of the server. No values need to be used in
the nodes, as there will be dynamic assigmet. This eliminates the dhcp
problem. Moreover it will eliminate the writes to EEProm unless we choose
to do it. In that case the server can hold a permanent NodeID assigment
list for the static nodes.

**Comment by TMRh20** [comment]
Hmm, interesting way of looking at it, this sounds like a good option.

**Comment by TMRh20** [comment]
Hey, just to clarify, is this something you would like to develop further, or is it ok for me to look at integrating this when I clean up the dhcplist stuff?

**Comment by spaniakos** [comment]
I would love to do it, but i need to do it after the 15 of the month. If
you want to do it earlier then do as you please :-) anyhow i can help

**Comment by TMRh20** [comment]
Per my experimentation here https://github.com/TMRh20/RF24Mesh/issues/43 it seems that some sort of unique identifier is required, so I'll close this issue unless somebody figures out a way...

**Pull request closed without merging**
